import { Order, SystemConfig, ReturnRecord, Expense } from '../types';

/**
 * Generates the HTML string for the receipt.
 * Optimized for thermal printers with a precise 0.5-inch (12.7mm) bottom tail.
 */
export const generateReceiptHtml = (
  config: SystemConfig, 
  order: Order | null, 
  type: 'RECEIPT' | 'KITCHEN' | 'KITCHEN_UPDATE' | 'VOID' | 'TEST' | 'BAR' | 'BAR_UPDATE' | 'SHIFT_REPORT',
  extraData?: any,
  printedBy?: string 
): string => {
  const currency = config.currency || 'UGX';
  const fontSize = config.receipt.fontSize || 12;
  const paperWidth = config.receipt.paperWidth || '80mm';
  
  // HARDCODED SYSTEM SUPPORT - Editable only by Master via SystemConfig
  const SYSTEM_SUPPORT = "+256 74-1350 786";
  const printInitiator = printedBy || "System Admin";

  const isKOT = ['KITCHEN', 'KITCHEN_UPDATE', 'BAR', 'BAR_UPDATE'].includes(type);

  const sharedStyles = `
    @media print {
        @page { margin: 0; size: auto; }
        body { margin: 0; }
    }
    html { margin: 0; padding: 0; background: #fff; height: auto; }
    body {
      padding: ${isKOT ? '1mm 2mm 12.7mm 2mm' : '4mm 6mm 12.7mm 6mm'}; 
      width: ${paperWidth};
      font-family: 'Courier New', Courier, monospace;
      font-size: ${fontSize}pt;
      color: #000;
      box-sizing: border-box; 
      margin: 0;
      height: auto;
      overflow-wrap: break-word;
      word-wrap: break-word;
      line-height: 1.1;
    }
    .text-center { text-align: center; }
    .bold { font-weight: bold; }
    .divider { border-top: 1px dashed #000; margin: 1.5mm 0; }
    .row { display: flex; justify-content: space-between; margin-bottom: 0.8mm; }
    .item-qty { width: 12%; font-weight: bold; }
    .item-name { width: 58%; }
    .item-price { width: 30%; text-align: right; font-weight: bold; }
    .small { font-size: 0.85em; }
    .footer-note { font-size: 0.8em; margin-top: 2mm; text-transform: uppercase; }
    .header-kot { font-size: 1.1em; border: 1.5px solid #000; padding: 1.5mm; margin-bottom: 1.5mm; }
  `;

  if (type === 'SHIFT_REPORT' && extraData) {
      const d = extraData;
      const now = new Date();
      
      return `
        <!DOCTYPE html>
        <html>
        <head><style>${sharedStyles}</style></head>
        <body>
            <div class="text-center bold" style="font-size: 1.2em;">${config.name}</div>
            <div class="text-center bold">SHIFT AUDIT REPORT</div>
            <div class="text-center small">${now.toLocaleString()}</div>
            <div class="divider"></div>
            
            <div class="bold small">FINANCIAL RECONCILIATION</div>
            <div class="row"><span>Opening Cash:</span> <span>${currency} ${d.openingCash.toLocaleString()}</span></div>
            <div class="row"><span>(+) Cash Sales:</span> <span>${currency} ${d.cashRevenue.toLocaleString()}</span></div>
            <div class="row"><span>(-) Expenses:</span> <span>${currency} ${d.totalExpenses.toLocaleString()}</span></div>
            <div class="divider"></div>
            <div class="row bold"><span>Expected Drawer:</span> <span>${currency} ${d.netCash.toLocaleString()}</span></div>
            
            <div class="divider"></div>
            <div class="bold small">DIGITAL & OTHER COLLECTIONS</div>
            <div class="row"><span>Mobile Money:</span> <span>${currency} ${d.momoRevenue.toLocaleString()}</span></div>
            <div class="row"><span>Cards/Bank:</span> <span>${currency} ${d.cardRevenue.toLocaleString()}</span></div>
            <div class="row"><span>Staff Salary Pay:</span> <span>${currency} ${d.staffDebt.toLocaleString()}</span></div>
            <div class="divider"></div>
            <div class="row bold"><span>Total Revenue:</span> <span>${currency} ${d.totalRevenue.toLocaleString()}</span></div>

            <div class="divider"></div>
            <div class="bold small">AUDIT: VOIDS & DELETIONS</div>
            <div class="row"><span>Total Orders:</span> <span>${d.totalOrders}</span></div>
            <div class="row"><span>Voided Items/Orders:</span> <span>${d.voidCount || 0}</span></div>
            
            <div class="divider"></div>
            <div class="footer-note text-center">
                <div class="bold">Report Generated By:</div>
                <div style="font-size: 1.1em; color: #000;">${printInitiator}</div>
            </div>
            <div class="text-center small" style="margin-top: 4mm;">
                <div class="bold">SYSTEM SUPPORT: ${SYSTEM_SUPPORT}</div>
                <div>Powered by EAGLE 🦅 EYED POS</div>
            </div>
        </body>
        </html>
      `;
  }

  // Bar Ticket
  if (type === 'BAR' || type === 'BAR_UPDATE') {
      let itemsHtml = '';
      if (order) {
        order.items.forEach(item => {
          if (type === 'BAR_UPDATE' && !item.isNew) return;
          itemsHtml += `
            <div class="row" style="align-items: flex-start;">
              <div class="item-qty">${item.quantity}x</div>
              <div class="item-name">${item.product.name.toUpperCase()}</div>
              <div class="item-price">${(item.product.price * item.quantity).toLocaleString()}</div>
            </div>
            ${item.note ? `<div class="small italic" style="margin-bottom: 1mm;"> >> ${item.note}</div>` : ''}
          `;
        });
      }

      return `
        <!DOCTYPE html>
        <html>
        <head><style>${sharedStyles}</style></head>
        <body>
            <div class="text-center">
                <div class="bold header-kot">TABLE: ${order?.table || 'WALK-IN'}</div>
                <div class="small bold">BAR TOKEN | ${type === 'BAR_UPDATE' ? 'ADD-ON' : 'NEW'}</div>
            </div>
            <div class="divider"></div>
            <div class="row small"><span>WAITER:</span> <span class="bold">${(order?.staffName || 'Staff').toUpperCase()}</span></div>
            <div class="row small"><span>TIME:</span> <span>${new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</span></div>
            <div class="divider"></div>
            <div class="items">${itemsHtml}</div>
            <div class="divider"></div>
            <div class="text-center bold small" style="opacity: 0.8; margin-top: 1mm;">--- BARMAN COPY ---</div>
            <div class="text-center small" style="margin-top: 2mm; opacity: 0.6;">SUPPORT: ${SYSTEM_SUPPORT}</div>
        </body>
        </html>
      `;
  }

  const headerTitle = {
    'RECEIPT': config.name,
    'KITCHEN': 'KITCHEN ORDER',
    'KITCHEN_UPDATE': '** KITCHEN ADD-ON **',
    'VOID': '** VOID SLIP **',
    'TEST': 'SYSTEM PRINT TEST'
  }[type] || config.name;

  let itemsHtml = '';
  if (order) {
    order.items.forEach(item => {
      if (type === 'KITCHEN_UPDATE' && !item.isNew) return;
      itemsHtml += `
        <div class="row" style="align-items: flex-start;">
          <div class="item-qty">${item.quantity}x</div>
          <div class="item-name">
            ${item.product.name.toUpperCase()}
            ${item.note ? `<div class="small italic" style="margin-top: 0.5mm;">Note: ${item.note}</div>` : ''}
          </div>
          ${(type === 'RECEIPT' || type === 'TEST' || type === 'VOID') ? 
            `<div class="item-price">${(item.product.price * item.quantity).toLocaleString()}</div>` : ''}
        </div>
      `;
    });
  }

  const isSalaryPay = order?.paymentMethod === 'SALARY_PAY';

  return `
    <!DOCTYPE html>
    <html>
    <head><style>${sharedStyles}</style></head>
    <body>
        <div class="text-center">
          ${(config.receipt.showLogo && config.logo && type === 'RECEIPT') ? `<img src="${config.logo}" style="max-width: 60%; margin-bottom: 2mm;" />` : ''}
          <div class="bold ${isKOT ? 'header-kot' : ''}" style="font-size: 1.1em;">${headerTitle}</div>
          ${type === 'RECEIPT' && config.receipt.headerText ? `<div class="small" style="margin-top: 1mm;">${config.receipt.headerText}</div>` : ''}
        </div>

        <div class="divider"></div>

        ${order ? `
          <div class="row small"><span>DATE/TIME:</span> <span>${new Date(order.timestamp).toLocaleString([], { dateStyle: 'short', timeStyle: 'short' })}</span></div>
          <div class="row small"><span class="bold">TABLE:</span> <span class="bold" style="font-size: 1.2em;">${order.table}</span></div>
          <div class="row small"><span>SERVED BY (WAITER):</span> <span class="bold">${(order.staffName || 'Staff').toUpperCase()}</span></div>
        ` : ''}

        <div class="divider"></div>
        <div class="items">${itemsHtml}</div>
        <div class="divider"></div>

        ${type === 'RECEIPT' && order ? `
          <div class="row bold" style="font-size: 1.1em;">
            <span>GRAND TOTAL</span>
            <span>${currency} ${order.grandTotal.toLocaleString()}</span>
          </div>
          <div class="row small" style="margin-top: 1mm;"><span>ITEMS COUNT:</span> <span>${order.items.reduce((acc, i) => acc + i.quantity, 0)}</span></div>
          ${order.paymentMethod ? `<div class="row small" style="margin-top: 2mm;"><span>PAYMENT MODE:</span> <span class="bold">${order.paymentMethod.replace('_', ' ')}</span></div>` : ''}
          
          <div class="divider"></div>
          <div class="footer-note">
              <div class="row"><span>CASHIER:</span> <span class="bold">${printInitiator.toUpperCase()}</span></div>
          </div>

          ${isSalaryPay ? `
            <div class="divider"></div>
            <div class="small">
                <div class="text-center bold" style="margin-bottom: 2mm; border: 1px solid #000; padding: 1mm;">SALARY PAY RECORD</div>
                <div class="row"><span>STAFF NAME:</span> <span class="bold">${(order.customerName || 'N/A').toUpperCase()}</span></div>
                <div style="margin-top: 6mm; border-bottom: 1.5px solid #000; width: 100%; height: 8mm;">SIGNATURE: </div>
                <div class="text-center" style="font-size: 0.7em; margin-top: 1mm; opacity: 0.8;">I authorize deduction from my salary</div>
            </div>
          ` : ''}
        ` : ''}

        <div class="divider"></div>
        <div class="text-center small">
            ${config.receipt.footerText ? `<div style="margin-bottom: 1mm;">${config.receipt.footerText}</div>` : ''}
            <div class="bold" style="font-size: 1.1em;">SYSTEM SUPPORT: ${SYSTEM_SUPPORT}</div>
            <div style="margin-top: 1mm; opacity: 0.7; font-size: 0.8em;">Powered by EAGLE 🦅 EYED POS</div>
        </div>
    </body>
    </html>
  `;
};

export const printReceipt = (
  config: SystemConfig, 
  order: Order | null, 
  type: 'RECEIPT' | 'KITCHEN' | 'KITCHEN_UPDATE' | 'VOID' | 'TEST' | 'BAR' | 'BAR_UPDATE' | 'SHIFT_REPORT',
  extraData?: any,
  printedBy?: string
) => {
  const htmlContent = generateReceiptHtml(config, order, type, extraData, printedBy);
  const iframe = document.createElement('iframe');
  Object.assign(iframe.style, { position: 'absolute', width: '0', height: '0', border: 'none', visibility: 'hidden' });
  document.body.appendChild(iframe);

  const doc = iframe.contentWindow?.document;
  if (!doc) return;

  doc.open();
  doc.write(htmlContent);
  doc.close();

  const triggerPrint = () => {
      if (iframe.contentWindow) {
          iframe.contentWindow.focus();
          iframe.contentWindow.print();
          setTimeout(() => { if (document.body.contains(iframe)) document.body.removeChild(iframe); }, 1000);
      }
  };

  if (doc.readyState === 'complete') triggerPrint();
  else iframe.onload = triggerPrint;
};

export const printTestReceipt = (config: SystemConfig, printedBy?: string) => {
    printReceipt(config, null, 'TEST', null, printedBy);
};